apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apnidunia
type: Opaque
stringData:
  POSTGRES_DB: apnidunia
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: apnidunia_pg_2024
  DATABASE_URL: postgresql://postgres:apnidunia_pg_2024@postgres-service:5432/apnidunia
  JWT_SECRET: apnidunia_secret_2024
